[
{"class": "momma_dragonn.end_of_epoch_callbacks.SaveBestValidModel",
 "kwargs": {"directory": "model_files"}},
{"class": "momma_dragonn.end_of_epoch_callbacks.PrintPerfAfterEpoch",
 "kwargs": {"print_trend": true}}
]
