[
{
    "other_data_loaders":[
    {
        "train": {
            "class": "hdf5_data_loader.MultimodalBatchDataLoader",
            "kwargs": {
                "path_to_hdf5": "train_data.hdf5",
                "num_to_load_for_eval": 20000
            }
        }
    }],
    "model_creator":{
        "class": "flexible_keras.FlexibleKerasGraph",
        "kwargs": {
           "config": {
                "inputs_config": [
                    {"name": "sequence",
                     "input_shape": [1, 4, 800]}
                ],
                "nodes_config": [
                {
                    "name": "conv1",
                    "input_name": "sequence", 
                    "class": "keras.layers.convolutional.Convolution2D", 
                    "kwargs": {"nb_filter": 300, "nb_row": 4, "nb_col": 10}
                },
                {
                    "name": "conv1_act",
                    "input_name": "conv1", 
                    "class": "keras.layers.core.Activation", 
                    "kwargs": {"activation": "relu"}
                },
                {
                    "name": "conv2",
                    "input_name": "conv1_act", 
                    "class": "keras.layers.convolutional.Convolution2D", 
                    "kwargs": {"nb_filter": 100, "nb_row": 1, "nb_col": 10}
                },
                {
                    "name": "conv2_act",
                    "input_name": "conv2", 
                    "class": "keras.layers.core.Activation", 
                    "kwargs": {"activation": "relu"}
                },
                {
                    "name": "max_pool",
                    "input_name": "conv2", 
                    "class": "keras.layers.convolutional.MaxPooling2D", 
                    "kwargs": {"pool_size": [1,40], "strides": [1,40]}
                },
                {
                    "name": "output",
                    "input_name": "max_pool", 
                    "class": "keras.layers.core.Dense", 
                    "kwargs": {"output_dim": 1, }
                },
                {
                    "name": "output_act",
                    "input_name": "output", 
                    "class": "keras.layers.core.Activation", 
                    "kwargs": {"activation": "sigmoid"}
                }],
                "outputs_config": [
                   {"name": "output",
                    "input": "output_act"} 
                ]
                "optimizer_config": {
                    "class": "Adam",
                    "kwargs": {"lr": 0.001}
                },
                "loss_dictionary": {
                    "output": "binary_crossentropy"
                }  
            } 
        } 
    },
    "model_trainer":{
        "class": "keras_model_trainer.KerasFitGeneratorModelTrainer",
        "kwargs": {
            "samples_per_epoch": 50000,
            "stopping_criterion_config": {
                "class": "EarlyStopping" ,
                "kwargs": {
                   "max_epochs": 300, 
                   "epochs_to_wait": 20
                } 
            },
            "class_weight": {0:1, 1:25}
        }
    }
}
]
