[
    {
        "other_data_loaders":[
            {
                "train": {
                    "class": "momma_dragonn.data_loaders.hdf5_data_loader.MultimodalBatchDataLoader",
                    "kwargs": {
                        "path_to_hdf5": "train_data.hdf5",
                        "num_to_load_for_eval": 20000
                    }
                }
            }],
        "model_creator":{
            "class": "momma_dragonn.model_creators.flexible_keras.FlexibleKerasGraph",
            "kwargs": {
               "config": {
                    "input_layers_config": [],
                    "nodes_config": [],
                    "optimizer_config": {},
                    "loss_dictionary": {}  
                } 
            } 
        },
        "model_trainer":{
            "class": "momma_dragonn.model_trainers.keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs": {
                "samples_per_epoch": 50000,
                "stopping_criterion_config": {
                    "class": "momma_dragonn.stopping_criteria.EarlyStopping" ,
                    "kwargs": {
                       "max_epochs": 300, 
                       "epochs_to_wait": 20
                    } 
                }
            }
        }
    }
]
